name: Slither-Test

on:
  workflow_call:

jobs:
  Slither-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from caller repo
        uses: actions/checkout@v4

      - name: Checkout solidity workflows repository
        uses: actions/checkout@v4
        with:
          repository: The-Poolz/solidity-workflows
          ref: master
          path: solidity-workflows

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Restore node modules cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        id: slither
        with:
          node-version: 20.9.0
          fail-on: high
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/

      - name: Comment on pull request
        if: github.event_name == 'pull_request' && env.exists == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: gasReport.md
          comment_tag: 'gas_report'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
